--- 
services:
  vaultwarden:
    image: ghcr.io/dani-garcia/vaultwarden:latest
    container_name: vaultwarden
    environment:
      - TZ=${TZ}
      - SIGNUPS_ALLOWED=${SIGNUPS_ALLOWED}
      - ADMIN_TOKEN=${ADMIN_TOKEN}
      - WEBSOCKET_ENABLED=${WEBSOCKET_ENABLED}
      - ORG_EVENTS_ENABLED=${ORG_EVENTS_ENABLED}
      - PASSWORD_ITERATIONS=${PASSWORD_ITERATIONS}
    volumes:
      - ${APPDATA}/vaultwarden:/data
    restart: unless-stopped
#
  vaultwarden-backup:
    image: bruceforce/vaultwarden-backup:latest
    container_name: vaultwarden-backup
    init: true
    environment:
      - TZ=${TZ}
      - UID=${BACKUP_UID}
      - GID=${BACKUP_GID}
      - BACKUP_ON_STARTUP=${BACKUP_ON_STARTUP}
      - DELETE_AFTER=${DELETE_AFTER}
      - TIMESTAMP=${TIMESTAMP}
      - CRON_TIME=${CRON_TIME}
    volumes:
      - ${APPDATA}/vaultwarden:/data #vaultwarden source data
      - ${APPDATA}/vaultwarden/backups:/backup #backup destination
    restart: unless-stopped
    depends_on:
      - vaultwarden
#
#
#
networks:
  default:
    name: ${CONNET}
    external: true